### ISSUE TITLE
mesecons-only doors

### ISSUE THREAD

**Issue by thomasrudin** [D00Med/scifi_nodes#24]

**Comment by thomasrudin** [comment]
@D00Med @Grossam my plan is here to add additional doors (copy the current definitions) which are mesecon-only opening.
~~**And optionally:** retire the `doors_open_with_mesecon_only` setting for existing doors~~

Feel free to object if you have issues with that... :smile:

**Comment by Grossam** [comment]
New doors are always welcommed : the default mod offers too few. The creations off bigger doors (2x4 !) is also worth considering.

Anyway, in my opinion, the mod would be more consistent if you kept the option. It offers freedom to serv admins.

**Comment by D00Med** [comment]
So you're saying there should be copies of the doors that only work with mesecons? They'd have to be present only if mesecons was. 

Btw, I forget how it works but would you two like to become proper contributors? so you can go ahead and merge stuff?

**Comment by thomasrudin** [comment]
> Btw, I forget how it works but would you two like to become proper contributors? so you can go ahead and merge stuff?

Sure, i'd love to. But bigger changes should still be discussed with you in the form of pull-requests...

**Comment by BuckarooBanzay** [comment]
closing this, mesecons-only doors are possible with settings now (thanks to @Grossam)
