### ISSUE TITLE
Replace non-free sounds

### ISSUE THREAD

**Issue by Wuzzy2** [D00Med/scifi_nodes#31]
Two sounds are under the bad/non-free CC BY-NC 3.0 licence:

* scifi_nodes_door_mechanic.ogg primeval_polypod https://freesound.org/people/primeval_polypod/sounds/156507/
* scifi_nodes_digicode.ogg https://freesound.org/people/Robinhood76/sounds/94933/

Please replace those sounds with libre ones OR we somehow convince the authors to grant us a free content license like CC BY or CC BY-SA.

The latter sound, actually, is so trivial that I think it can be recreated easily. This is just telephone digit dial sounds for 01592, I bet it can be recreated in Audacity.

**Comment by BuckarooBanzay** [comment]
@Grossam ^

**EDIT:** my bad, `scifi_nodes_door_mechanic.ogg` was introduced by me... :facepalm:

**Comment by Grossam** [comment]
Here's the summary ogf the licence : https://creativecommons.org/licenses/by-nc/3.0/

Isn't right to use theses sounds in Mineest ? It's a non-commercial use.

**Comment by Wuzzy2** [comment]
Well, it's not *technically* wrong in Minetest, HOWEVER, we're a free software project, and we very much prefer to use free software licensing everywhere. We value our freedom.

NonCommercial is not free/libre as it creates many problems, mainly, its incompatible with most free software projects.

If an alternative sound with CC0, CC BY or CC BY-SA is found, that would be great.
