### ISSUE TITLE
Many metal nodes make glass sounds

### ISSUE THREAD

**Issue by Wuzzy2** [D00Med/scifi_nodes#73]
For some reason, most nodes that are clearly made out of metal make glass sounds, for foostep and breaking. Breaking even makes a "glass shatter" sound.

Can this please be fixed and a metal sound be used for the metal nodes instead? Thanks.

**Comment by BuckarooBanzay** [comment]
> Can this please be fixed and a metal sound be used for the metal nodes instead? Thanks.

PR's welcome 👍
